### ISSUE TITLE
think its a viable mvp approach to take?

### ISSUE THREAD

**Issue by svenwoldt** [pathikrit/vocowl#2]
Hey Pathikrit,

I am digging through your script and was wondering if you see it as a viable approach to handle payments in production this way. I have read on webshell that all scripts are publicly executable at the moment. It does not provide secure https communication.
I tried to integrate a payment test given your tutorial but still not successful till now, mostly because I think webshell is responsible with strange error behavior. Do you regard this site as stable?
Thanks ind advance and kind regards,
Sven

**Comment by pathikrit** [comment]
Yeah I think it is stable. You can use a fake credit card (https://stripe.com/docs/testing) and pay me on http://vocowl.com
